server:
  port: 8901
spring:
  application:
    name: temp
  datasource:
    username: root
    password: Youedata@83#
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://172.16.4.83:3306/spring_boot?autoReconnect=TRUE&useUnicode=TRUE&characterEncoding=UTF-8&useSSL=FALSE&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    #host: 129.204.207.127
    database: 2 # Redis数据库索引（默认为0）,如果设置为1，那么存入的key-value都存放在select 1中
    host: 127.0.0.1
    port: 6379
    max-wait: 30000    # 连接池最大阻塞等待时间（使用负值表示没有限制）
    max-active: 100   # 连接池最大连接数（使用负值表示没有限制）
    max-idle: 20     # 连接池中的最大空闲连接
    min-idle: 0     # 连接池中的最小空闲连接
    timeout: 5000   # 连接超时
      #password: 123456 # 密码,默认密码为空
      #cluster:       # 集群配置
    #nodes: 127.0.0.1:6381,127.0.0.1:6382,127.0.0.1:6383,127.0.0.1:6384,127.0.0.1:6385,127.0.0.1:6386
    #max-redirects: 2  # 最大重定向次数
  kafka:
    bootstrap-servers:
      - 192.168.101.137:9091
      - 192.168.101.137:9092
      - 192.168.101.137:9093
    producer:
      retries: 0
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: foo
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 100
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  typeAliasesPackage: com.youedata.dataQualityEvaluation.model
  global-config:
    id-type: 0  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
    logic-delete-value: 0
    logic-not-delete-value: 1
    #sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用
daas-switch:
  swagger-open: true

#quartzJob
quartz:
  cron:
    test: 0 0/1 * * * ?

elasticsearch:
  host: localhost
  port: 9200
  connectNum: 10
  connectPerRoute: 50

logging:
  level.root: info
  level.com.stylefeng: info
  file:
    path: logs/